INSERT INTO PRODUCT (article, name, amount, price) VALUES (1, 'Laptop', 10, 1200.00);
INSERT INTO PRODUCT (article, name, amount, price) VALUES (2, 'Mouse', 50, 25.00);
INSERT INTO PRODUCT (article, name, amount, price) VALUES (3, 'Keyboard', 30, 75.00);
INSERT INTO PRODUCT (article, name, amount, price) VALUES (4, 'Monitor', 15, 300.00);
INSERT INTO PRODUCT (article, name, amount, price) VALUES (5, 'Webcam', 20, 50.00);
INSERT INTO PRODUCT (article, name, amount, price) VALUES (6, 'Headphones', 40, 100.00);
INSERT INTO PRODUCT (article, name, amount, price) VALUES (7, 'Microphone', 25, 70.00);
INSERT INTO PRODUCT (article, name, amount, price) VALUES (8, 'Speakers', 18, 150.00);
INSERT INTO PRODUCT (article, name, amount, price) VALUES (9, 'Printer', 12, 200.00);
INSERT INTO PRODUCT (article, name, amount, price) VALUES (10, 'Router', 22, 60.00);
INSERT INTO PRODUCT (article, name, amount, price) VALUES (11, 'External Hard Drive', 10, 80.00);
INSERT INTO PRODUCT (article, name, amount, price) VALUES (12, 'SSD', 15, 120.00);
INSERT INTO PRODUCT (article, name, amount, price) VALUES (13, 'USB Drive', 100, 15.00);
INSERT INTO PRODUCT (article, name, amount, price) VALUES (14, 'Charging Cable', 80, 10.00);
INSERT INTO PRODUCT (article, name, amount, price) VALUES (15, 'Power Bank', 30, 40.00);
INSERT INTO PRODUCT (article, name, amount, price) VALUES (16, 'Smartwatch', 20, 250.00);
INSERT INTO PRODUCT (article, name, amount, price) VALUES (17, 'Fitness Tracker', 35, 70.00);
INSERT INTO PRODUCT (article, name, amount, price) VALUES (18, 'Tablet', 8, 400.00);
INSERT INTO PRODUCT (article, name, amount, price) VALUES (19, 'Smartphone', 5, 800.00);
INSERT INTO PRODUCT (article, name, amount, price) VALUES (20, 'E-Reader', 10, 130.00);